<a href="https://colab.research.google.com/github/sayem1997/AIPII/blob/master/Quiz/Popcorn_Quiz(April_03).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Popcorn Quiz (April. 03)

Student ID:                              Student Name: 

### 1. NumPy arrays can explicitly be multi-dimensional (10 pts)
####  Creating the two-dimensional array (3 by 2) : Just use array() & range()


#### hint :: a = np.array([range(i, i + 3) for i in [1, 2, 3]])
            --> make two dimensional array(3 by 3). 

Display that result, dimension and shape

In [0]:
import numpy as np
# write your answers in here
a = np.array([range(i, i+2) for i in [1, 2, 3]])
print(a)


[[1 2]
 [2 3]
 [3 4]]


### 2. Create an array with values 0 to 49 using the np.arange() (10 pts)
#### condition: stepping by 2 

In [0]:
import numpy as np
# write your answers in here
b = np.arange(0, 50, 2)
print(b)




[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


### 3. Slicing (10 pts)
#### Write a Python program to create a 2d array as shown in the result array. And solve the problems. 
 

In [0]:
# raw data
import numpy as np
arr = np.array([[3,4,5,6], 
                [4,1,1,0],
                [1,4,7,4]])
arr

array([[3, 4, 5, 6],
       [4, 1, 1, 0],
       [1, 4, 7, 4]])

In [0]:
# 3-1.  Check the result and write your answer in below
x = arr[:, -1]
print(x)

# result : array([6,0,4])

[6 0 4]


In [0]:
# 3-2.  Check the result and write your answer in below
y = arr[:, :-1:2]
print(y)

#    array([[3, 5],
#          [4, 1],
#          [1, 7]])   

[[3 5]
 [4 1]
 [1 7]]


### 4. Write a Python program to create a 2d array and then adjust to the final array in below (just use indexing!!!)  (10 pts)

In [0]:
import numpy as np
arr = np.ones((4,4))
print("This is the raw array.")
arr
# the result array in below 
# array([[1., 1., 1., 1.],
#        [2., 0., 0., 0.],
#        [2., 0., 0., 0.],
#        [3., 3., 3., 3.]])

This is the raw array.


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
# Write your answer in here
for i in range(4):
  for j in range(4):
    if i == 3:
      arr[i][j] += 2
    if i > 0 and i < 3:
      if j == 0:
        arr[i][j] += 1
      else:
        arr[i][j] -= 1

arr



array([[1., 1., 1., 1.],
       [2., 0., 0., 0.],
       [2., 0., 0., 0.],
       [3., 3., 3., 3.]])

ERROR! Session/line number was not unique in database. History logging moved to new session 60


In [0]:
Good Job!