<a href="https://colab.research.google.com/github/sayem1997/AIPII/blob/master/Assignments/Solution_Tensorflow_Practice_II(Student)_TF2(May_15).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1 Tensorflow

In [0]:
import tensorflow as tf
tf.__version__

'2.2.0'

## 2 Our first tensorflow program: Hello world

In [0]:
h = tf.constant("Hello")
w = tf.constant(" world")
hw = h + w
print(hw)

tf.Tensor(b'Hello world', shape=(), dtype=string)


## 3 Key concepts of Tensorflow
- Computation graph
- Execution

## 4 Computation graph
- Nodes & Edges
- Operations
- Benefits of graph computation

![Computation Graph](https://i.ibb.co/ct6r840/Cap-2020-05-14-08-07-08-859.jpg)

- We create 5 nodes assigned to arbitrarily named variables, a ~ e
- The contents of these variables should be regarded as the output of the operation, not operation
themselves
- But for now we refer to both the output of the operation and operation themselves with the
names of corresponding variables.

In [0]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)
d = tf.multiply(a,b)
e = tf.add(c,b)
f = tf.subtract(d,e)

## 5 Execution

In [0]:
print("out = {}".format(e))

out = 5


## 6 Creating a computation graph (deprecated)

In [0]:
g1 = tf.Graph() # generate new graph
print(g1)

## 7 What is Session? (deprecated)
- Tensorflow’s computation system runs on GPUs which have independent memory system
and calculators.
- So, we need to associate python objects and data on our end with the computation system
- Session object is a Tensorflow object for the association

## 8 Execution (deprecated)

## 9 Flowing Tensors
- Node = Operation
- Edge = Tensor

In [0]:
# This operation creates actual operation instance and result
f = tf.add(e, d) 

In [0]:
print(f) # print computed actual value

tf.Tensor(15, shape=(), dtype=int32)


### 9.0.1 Setting attributes for tensor and operations
- name, shape, dtype, . . .

In [0]:
f = tf.add(e, d, name='Addition_E_D') # shape and dtype of operation are automatically
print(f)

tf.Tensor(15, shape=(), dtype=int32)


In [0]:
h = tf.constant([1,2,3], name='const_3', dtype=tf.float32)
print(h)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


## 10 Tensor
### 10.0.1 1) is the name of an object used in the python api as a handle for the result of an operation in the graph.
### 10.0.2 2) is also a mathematical term for n-dimensional arrays
- 1 x 1 tensor = scalar
- 1 x n tensor = vector
- n x n tensor = matrix
- n x n x n tensor = 3-dimensional array
- . . .

In [0]:
# Eager execution ; an imperative programming environment that evaluates operations immediately, without builing grphs
# first example 
a = [[2.]]
b = tf.matmul(a,a)
print("result, {}".format(b))

result, [[4.]]


In [0]:
a = tf.constant([[1,2], [3,4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [0]:
# broadcasting 
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [0]:
# operator overloading is okay
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [0]:
import numpy as np
c = np.multiply(a,b)
print(c)

[[ 2  6]
 [12 20]]


In [0]:
# obtain numpy value from a tensor
print(a.numpy())

[[1 2]
 [3 4]]


In [0]:
# fizzbuzz
def fizzbuzz(n):
  counter = tf.constant(0)
  n = tf.convert_to_tensor(n)
  for i in range(1, n.numpy()+1):
    i = tf.constant(i)
    if int(i % 3) == 0 and int(i % 5) == 0:
      print("FizzBuzz")
    elif int(i % 3) == 0:
      print("Fizz")
    elif int(i % 5) == 0:
      print("Buzz")
    else:
      print(i.numpy())
    counter += 1

In [0]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [0]:
# loss function : MSE loss for regression 
# for classification, we will use "sparse_categorical_crossentropy "
# Since the task here is performing multi-class classification, 
# you will need to find the loss for each class label and sum the result. 


$$loss = -\sum_{j=0}^{n}y_{true, j}*\log(p_{pred, j})$$


In [0]:
# n : number of classed 
# y_true : True label of the data
# P_pred : Prediction probability vector for the data 